### ISSUE TITLE
This is awesome!

### ISSUE THREAD

**Issue by sethvargo** [trinitronx/strainer-berkshelf-chefspec-demo-cookbook-repo#1]
Let me know if you need any help!

**Comment by trinitronx** [comment]
Hehe, thanks!

I just realized that one of the factors that was causing the recursive `vendor/cookbooks` folder creation was the [`berksfile.install` line](https://github.com/trinitronx/strainer-berkshelf-chefspec-demo-cookbook-repo/blob/master/cookbooks/strainer-berkshelf-chefspec-recursive-bug/spec/spec_helper.rb#L31) in my `spec/spec_helper.rb`.  I remember looking at this one day, and realizing that there is currently no equivalent to `bundle check` for Berkshelf, which would avoid doing multiple `berks install`s.  However, if Strainer is doing it's own dependency management, perhaps it should ignore the vendor/cookbooks dir?

**Comment by sethvargo** [comment]
@trinitronx if you think `berks check` (or something equivalently named) would be helpful, please open an issue on BS and describe the use case. Bonus points if you write cucumber features describing exactly how it would behave :smile:.
